appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: b8mPLUYIbKY3lSdg+O2ltB8LCnJzPSCi4zpca6dH+O9Oj8GaK7hr9G1ZGLeWi35sS1GV3BUUwVJ3tj/+rWuY5IVYtATWU5qKFEqxS+0/wOAKVjux0uJxJ5kNvhCSuSIzZc4Y/+zeVO6aY+IC3DG4w4KSR9Gv1o64YY2E1fZrR+Frta+w4DEuJ+MO5RryjXbg3QidGbV9VORrVry8hBzKLtvU57ZG+psrGLwaw3ZU7HpdDQdPsDIK+lBwCcva5T/GIdrUrP9x0UTswELc5rB/ja4kes7B1cDpKWhICOxjhsCNDPlVAJardRctITTSKeZSYL00HlH2Kj/Tg2Hojpn908M6Rs4QvIl4oqVlM0ayU+nWUZEaWASkbUfKH8rdXy2VEuE5yDRtm1WVMDwT0qNohh34KD2R/scPNwXFk3jG+EWFJtpJ1IrMbi0k1Cf8ko3OnIYjQQv6ZB5XwBvnTBChxu7n96Sr4B+kMDaBmsTMq0RPIh1SekB4cRHfKkw3CHyQvuzbv0GAY8vRcvO+3ThlDClai1HnO0iNLLnOT4+3WIu4HImHkrK0/mpoyMQwWBPNBNpgBCJ2aNcRQMR7cj8e0Zp7YHE0DXRF3JFDGhChRZf4eYcbzw2DyYXKK8PfKJNHtlfmxN6MdUqwOvBB9/6YeG2MgxVhgIeFOFT2d50ToVQ=}
